# Job that will download the other artifact from the build and will add a comment with the contents.
steps:

- template: ../common/checkout.yml

- template: ../build/download-artifacts.yml 
  parameters:
    runTests: false  # we do not run tests on builds
    enableAPIDiff: false  # we do not run the api diff here.

- pwsh: |
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\MaciosCI.psd1
    $artifact = New-ArtifactsFromJsonFile -Path "$Env:ARTIFACTS_JSON_PATH"
    $gihubComments = New-GitHubCommentsObject -Org "xamarin" -Repo "xamarin-macios" -Token $Env:GITHUB_TOKEN -Hash $Env:GIT_HASH
    $result = $gihubComments.NewCommentFromObject("Artifacts", ":books:", $artifact)
    Write-Host $result
  env:
    BUILD_REVISION: $(Build.SourceVersion)
    GITHUB_TOKEN: $(GitHub.Token)
    ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Create github comment.'
  enabled: true
  timeoutInMinutes: 10

