parameters:

- name: keyringPass
  type: string

- name: skipESRP
  type: boolean
  default: false # only to be used when testing the CI and we do not need a signed pkg

- name: signingSetupSteps
  type: stepList
  default: []

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

- name: packages
  type: object
  default: []

jobs:
- ${{ each pkg in parameters.packages }}:
  - job: ${{ pkg.job }}
    dependsOn:
    displayName: 'Sign & Notarize ${{ pkg.name }}'
    condition: ne(stageDependencies.configure_build.configure.outputs['configure_platforms.${{ pkg.conditionVariable }}'],'')
    timeoutInMinutes: 1000
    pool:
      vmImage: internal-macos-11
    workspace:
      clean: all

    steps:
    - template: sign-and-notarized.yml
      parameters:
        isPR: ${{ parameters.isPR }}
        repositoryAlias: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.commit }}
        signingSetupSteps: ${{ parameters.signingSetupSteps }}
        keyringPass: ${{ parameters.keyringPass }}
        skipESRP: ${{ parameters.skipESRP }}
        packageName: ${{ pkg.name }}
        packagePattern: ${{ pkg.pattern }}
