# all steps that are required to publish the nugets

parameters:
- name: isPR
  type: boolean

steps:

# do not publish on pull requets
- ${{ if not(parameters.isPR) }}:
  - task: NuGetCommand@2
    displayName: 'Publish Nugets to dotnet-eng'
    inputs:
      command: push
      packagesToPush: $(Build.SourcesDirectory)/mlaunch/*.nupkg
      nuGetFeedType: external
      publishFeedCredentials: dotnet-eng
    condition: and(succeeded(), eq(variables['configuration.BuildNugets'], 'True'))
    continueOnError: true # should not stop the build since is not official just yet.

# Only executed when the publishing of the nugets failed.
- bash: |
    echo "##vso[task.setvariable variable=NUGETS_PUBLISHED;isOutput=true]Failed"
  name: nugetPublishing
  displayName: 'Failed publishing nugets'
  condition: failed()
