# template that setups all the diff plugins needed to perform the sign and notarize step
parameters:

- name: signatureType
  type: string
  default: 'Real'

- name: condition
  default: and(succeeded(), eq(variables['IsPRBuild'], 'False'))

steps:

# DO NOT USE THE checkout.yml template. The reason is that the template changes the hash which results in a problem with the artifacts scripts
- checkout: self          # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout
  clean: true             # Executes: git clean -ffdx && git reset --hard HEAD
  submodules: recursive
  path: s/xamarin-macios

- checkout: maccore
  clean: true
  persistCredentials: true  # hugely important, else there are some scripts that check a single file from maccore that will fail

- checkout: templates
  clean: true

- checkout: release-scripts
  clean: true

# the ddsign plugin needs this version or it will crash and will make the sign step fail
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 3.x
  displayName: 'Install .NET Core SDK 3.x needed for ESRP'

- task: MicroBuildSigningPlugin@3
  displayName: 'Install Signing Plugin'
  inputs:
    signType: '${{ parameters.signatureType }}'
    azureSubscription: 'MicroBuild Signing Task (DevDiv)'
    zipSources: false  # we do not use the feature and makes the installation to last 10/12 mins instead of < 1 min
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  condition: ${{ parameters.condition }}

- task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@3
  displayName: 'Install Notarizing Plugin'
  inputs:
    signType: 'Real'  # test is not present for mac..
    azureSubscription: 'MicroBuild Signing Task (DevDiv)'
    zipSources: false  # we do not use the feature and makes the installation to last 10/12 mins instead of < 1 min
  env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  condition: ${{ parameters.condition }}
