steps:

- checkout: self
- checkout: maccore
  persistCredentials: true  # hugely important, else there are some scripts that check a single file from maccore that will fail

- task: CredScan@3
  displayName: "Run CredScan"
  inputs:
    suppressionsFile: '$(System.DefaultWorkingDirectory)/maccore/tools/devops/CredScanSuppressions.json'
  
- powershell: |
    Write-Host 'Source dir $(Build.SourcesDirectory)'
    Write-Host 'Working dir $System.DefaultWorkingDirectory)'

    Dir $(Build.SourcesDirectory)
    Dir $(System.DefaultWorkingDirectory)
  displayName: Dump enviroment

- powershell: |
    gci env: | format-table -autosize -wrap
  displayName: 'Dump Environment'

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'

- task: PoliCheck@1
  inputs:
    inputType: 'Basic'
    targetType: 'F'
    targetArgument: '$(Build.SourcesDirectory)'
    result: 'PoliCheck.xml'
    optionsUEPATH: '$(System.DefaultWorkingDirectory)/maccore/tools/devops/PoliCheckExclusions.xml'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
  displayName: 'Post Analysis'
  inputs:
    CredScan: true
    PoliCheck: true