blank_issues_enabled: true
contact_links:
  - name: "MAUI"
    url: https://github.com/dotnet/maui/issues/new/choose
    about: Issues with MAUI
  - name: "‚öô Bug report or feature request for Visual Studio (for Windows)"
    url: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022
    about: Use Visual Studio's Report a Problem feature for issues and suggestions with Visual Studio tooling. This includes problems with connecting to remote Macs from Visual Studio.
  - name: "‚öô VSCode"
    url: https://github.com/microsoft/vscode-dotnettools/issues
    about: Issues with VSCode.
  - name: "üôã‚Äç‚ôÄÔ∏è Community Support"
    url: https://learn.microsoft.com/en-us/answers/products/97/dotnet/
    about: For issues that likely aren't bugs, Microsoft Q&A is a good place to ask for help.
