# iOS device pipeline, this file sets the different parameters required by the device-tests-common-yml, which contains all the steps and the interesting logic.

# lame! cannot have the resources in the template.. :/
parameters:
- name: disableProviCleanup
  type: boolean
  default: false

- name: clearProviCache
  type: boolean
  default: false

resources:
  repositories:
  - repository: maccore
    type: github
    name: xamarin/maccore
    ref: refs/heads/device-tests-yaml # should this be on a branch and not on master???
    endpoint: xamarin

variables:
    - group: xamops-azdev-secrets

jobs:
- template: device-tests-common.yml # all the smart stuff happens in the template, just needed to set the params
  parameters:
    name: 'macOS'
    displayName: 'Run iOS Device Tests'
    pool: 'VSEng-Xamarin-Mac-Devices'
    demands: 'ios'
    statusContext: 'iOS-DDFun'
    testsLabels: '--label=run-ios-64-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
    disableProviCleanup: ${{ parameters.disableProviCleanup }}
    clearProviCache: ${{ parameters.clearProviCache }}
