# Template that contains the default variables to be used by all the diff test pipelines.
variables:
  - group: xamops-azdev-secrets
  - group: Xamarin Release
  - group: Xamarin-Secrets
  - name: VSDropsPrefix
    value: 'https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests'
  - name: WindowsDevicePool
    value: 'VSEngDeploymentPool'

