# all steps that are required to publish the nugets, the template takes the parameters to decide in which feed should the nugets
# be published
steps:

# based on the build, decide if we are used a feed or the other and export it
- bash: |
    set -x
    set -e
    make
    var=$(make -C $(Build.SourcesDirectory)/xamarin-macios/tools/devops print-variable VARIABLE=$VAR_NAME)
    var=${var#*=}
    echo "##vso[task.setvariable variable=Credential]$var"
  displayName: 'Retrieve nuget feed'
  name: ConfigureNuget
  env:
    ${{ if not(contains (variables['Build.Repository.ID'], 'private')) }}:
      VAR_NAME=NUGET_PUBLIC_FEED
    ${{ if contains (variables['Build.Repository.ID'], 'private') }}:
      VAR_NAME=NUGET_PRIVATE_FEED

- task: NuGetAuthenticate@0
  displayName: 'Authenticate dotnet-tool feed'
  inputs:
    nuGetServiceConnections: $(ConfigureNuget.Credential)
  condition: contains (variables['Build.Repository.ID'], 'private')

- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: nuget-signed
    downloadPath: $(Build.SourcesDirectory)/package
    patterns: |
      *.nupkg

- task: NuGetCommand@2
  displayName: Publish Nugets to dotnet6
  inputs:
    command: push
    packagesToPush: $(Build.SourcesDirectory)/package/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: $(ConfigureNuget.Credential)

- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: vs-msi-nugets
    downloadPath: $(Build.SourcesDirectory)/vs-msi-nugets
    patterns: |
      *.nupkg

- task: NuGetCommand@2
  displayName: Publish Nugets to dotnet6
  inputs:
    command: push
    packagesToPush: $(Build.SourcesDirectory)/vs-msi-nugets/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: $(ConfigureNuget.Credential)
