name: Clean PR macios.ci data

on:
  pull_request:
    types: [closed]

# lock to ensure we do not step on each other
concurrency: 
  group: 'macios.ci-cleanup'
  cancel-in-progress: false

jobs:
  clean-up:
    runs-on: ubuntu-latest
    name: Clean PR data

    steps:
    - run: echo "$GITHUB_CONTEXT"
      name: 'Debug context'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - uses: actions/checkout@master
      with:
        name: xamarin/macios.ci
        github_token: ${{ secrets.GITHUB_TOKEN }}
        path: macios.ci

    - run: |
        PR_DATA="pr/PR$PR_NUMBER"
        cd $MACIOS_CI_PATH
        ls "$MACIOS_CI_PATH/pr"
        if [[ -d "$PR_DATA" ]]; then
          git checkout -b "pr/clean/PR$PR_NUMBER"
          git rm -r $PR_DATA
          git commit -m"[Action] Remove data of PR $PR_NUMBER" -a
          git push origin "pr/clean/PR$PR_NUMBER" -f
        else
          echo "PR$PR_NUMBER has no data in the static page."
        fi
      name: 'Remove data'
      env:
        MACIOS_CI_PATH: ${{ github.workspace }}/macios.ci 
        PR_NUMBER: ${{ github.event.number }} 
